[package]
name = "rust-algos"
version = "0.1.0"
edition = "2021"

# Support math in Rust Doc like:
# https://github.com/victe/rust-latex-doc-minimal-example
[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "path-to-your-header-file.html" ]

[dependencies]
